### ISSUE TITLE
Task 1 Review

### ISSUE THREAD

**Issue by dimitarg** [apkirov/has-travel#1]
Здрасти,

Отдолу малко размисли за задача 1 с най-къс път в граф. За втората задачка ще ти върнем фийдбек във понеделник най-вероятно - не успях да се справя с perl , друг смелчага ще се пробва :)

Това е просто рецензия от моя страна. Не се очаква да пренаписваш кода спрямо препоръките и; нито да се съгласяваш на 100% с нея. Тук е за твоя информация/помощ, и общо казано отразява визията на Novarto за добър код.
# Коректност
- изглежда да работи коректно. Няма обаче какво да го демонстрира - по тази тема по-надолу
# Структури от данни

Ако типа на връх в графа е T (в нашия случай String, или даже Char, ако сме по-пестеливи), традиционно, ненасочен граф се моделира с Map [ T,Set [ T ] ](Другият често използван вариант е матрица на съседство boolean[][] . За целта трябва да изградиш съответствие между имената на върховете в графа и естествените числа 0 .. <number of nodes-1>. Има предимства и недостатъци на двата варианта)

Ти си направил горе-долу следното:
- HasVector е, грубо казано, наредена двойка от върхове 
- Имаш data: List [ HasVector ] , което пази raw инпута, тоест ребрата на графа
- Имаш Map [ String,List [ HasVector ] ] , пътищата от X до Y
- Имаш Map [ String,List [ HasVector ] ] , пътищата наобратно

Недостатъка спрямо единствен Map [ T , Set [ T ] ] е разточителност откъм памет.
# Стил на кода
- Всички методи в програмата са void и разчитат на странични ефекти върху mutable state. 
- Параметъра text на findPath се мутира вътре във функцията, тоест се позлва като input/output Параметър
- тъй като findPath е void, тоест няма return statement, е по-трудно да се разчете какво е дъното на рекурсията

Нашата визия е, че е най-добре една функция да взема вход, и да връща изход - точно като математическа функция. 
https://en.wikipedia.org/wiki/Referential_transparency_(computer_science)
Това прави кода по-четлив, по-модулярен, и threadsafe.
В конкретния случай, функцията findPath би могла да връща List [ Node]. В нашия случай Node = String Или пък Node = Char

Instance variables:

Имплементирането на алгоритъм често не изисква полиморфизъм, и в такива случаи се прави всичко да е static (разбира се, за целта се изисква да нямаш mutable state).  Подобен стил можеш да видиш в java.lang.Math
# Tестове

Много се надявах да видя автоматизирани тестове за програмата. Освен че помагат да подсигурим коректността, служат и като изпълнима документация на кода.

Това е от мен засега.
Поздрави, Митака

**Comment by apkirov** [comment]
Разбира се, всичко което написа тук е вярно

Като най-тежка грешка смятам липсата на автоматизирани тестове за
програмата.
Поне по логиката, която тук си описал.

По това което си написал има следните забележки:
1) не сте искали "автоматизирани тестове за програмата", не сте получили.
Прави сте, трябваше да се сетя, но не съм...
2) "Нашата визия е, че е най-добре една функция да взема вход, и да връща
изход - точно като математическа функция" - доста обширен въпрос, особено
ако се търси бързодействие. Дали  една фукнция е VOID или връша List, което
пак е някакъв смахнат тип данна, когато го дебъгваш (второто) ще се
побъркаш кое в кое се присвоява. Отделен е въпроса, метод който връша List
или друг ArrayClass type, колко малко памет използва.

За съжаление това си е чисто статистическа задача. Тук няма виша логика или
математика, тук си има най-обикновенна комбинаторика. Комбинаториката се
отличава с това, че трябва да извъртиш всички комбинации за да си сигурен,
че си поличил най-добрия резултат. Нама друг начин. Това което съм направил
е просто метод, който рекурсивно обходжа възможните маршрути.
Този подход е по-скоро C-style. Там където се работи с pointer-и....
Също така системата е "проектирана" (малко пресилен израз :)) да работи с
имена по-дълги от 1 символ, затова са стрингове. На всички е ясно, че ако
сменим String с char нещата ще започнар да изглеждат доста по-различно от
към скорост.
Относно "boolean[][] " - аз съм най-големият противник на това, програмист
на Java да използва примитивни типове за логиката си. Ако ще използваме
boolean[][]  или char или нещо такова тогава е по-практично да се пише на C.
Затова не съм го направил така, а съм го вкарал във някакъв помощен обект
HasVector.

И най-важното - това все пак е тест, а не е реална система. Не познавам
вашия стил на писане - все пак работя другаде, но съм сигурен, че лесно ще
навляза
За втората задака - ако не ви харесва perl-a мога  да го напиша и на нещо
друго - просто се изкуших заради това, че ще е на 5 реда

Ангел

2015-10-16 15:50 GMT+03:00 Dimitar Georgiev notifications@github.com:

**Comment by dimitarg** [comment]
Мисля,че Perl е подходящ за втората задача.

> > 1) не сте искали "автоматизирани тестове за програмата", не сте получили.

Споменах устно и писмено.
Откъс от мейла: 

"Неща, които ще се смятат за плюс:
- Pure functions
- Immutable data structures
- Non-imperative solution of problems -- recursion, higher-order functions on data structures - fold, map, flatMap, zip, collect, partition, etc
- Automated tests"

...
Относно забележката за бързодействието - можеш да връщаш String[] . Въпроса е да го връщаш във return type, а не да мутираш параметър на метода. 

Ако ти е интересно да научиш повече за тази парадигма, можеш да прегледаш някое от следните неща, в зависимост на какво ти се пише. Принципите са едни и същи

https://github.com/MostlyAdequate/mostly-adequate-guide
(JavaScript)

https://www.coursera.org/course/progfun
(Scala)

http://learnyouahaskell.com/chapters
(Haskell)
